### PR TITLE
Added configuration option for item weight.

### PR DESCRIPTION
**Pull request by WolfieWaffle**
I think it works fine, but if not tell me. This makes it so you can change the default weight of items.

### CODE REVIEW

**Comment by WolfieWaffle** [comment]
OK, I'll try and fix those right now.

**Comment by WolfieWaffle** [comment]
"This will always return 0, unless you set the config option to below 0"

Really? I thought that if if you put it to 1, it would always return 1 unless you made it greater than 1. I'll try putting it back to 0.

**Comment by Parker8283** [comment]
Read my new comment

**Comment by WolfieWaffle** [comment]
Oh, I didn't see that, nevermind. I fixed the other two and I'm committing it.

**Comment by WolfieWaffle** [comment]
There, the unnecessary multiply by 1 and cast to double are gone.

**Comment by Parker8283** [comment]
Should be in the latest snapshot shortly.

**Comment by WolfieWaffle** [comment]
Thanks!

**Pull request merged**
